name: diagnostico
description: App for get data of students

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  gsheets: ^0.4.2
  firebase_core: ^1.17.1
  cloud_firestore: ^3.1.17
  sembast: ^3.2.0
  path_provider: ^2.0.10
  get_it: ^7.2.0
  animated_splash_screen: ^1.2.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.3

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon/icon.png"
  # adaptive_icon_foreground: "assets/icon/icon.png"
  # adaptive_icon_background: "#FF0000"
  # adaptive_icon_padding: true

flutter:

  uses-material-design: true
  assets:
    - assets/icon/icon.png
