// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1QUX6iY8MyiK6mRw14k1Aua-fNuS_2oc',
    appId: '1:737119538560:web:580acafa340ba38aa5c565',
    messagingSenderId: '737119538560',
    projectId: 'dulcineia-ee8f1',
    authDomain: 'dulcineia-ee8f1.firebaseapp.com',
    storageBucket: 'dulcineia-ee8f1.appspot.com',
    measurementId: 'G-3JXGJD0G62',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-hPADFo5u8jCBwFL2GohVf9KO3xk2fgw',
    appId: '1:737119538560:android:d4d3d5981fb782ffa5c565',
    messagingSenderId: '737119538560',
    projectId: 'dulcineia-ee8f1',
    storageBucket: 'dulcineia-ee8f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNxwpO1rfPbB_rV9GZYtNi1Bt_2_ZBkcA',
    appId: '1:737119538560:ios:e1d9cd37a469466ea5c565',
    messagingSenderId: '737119538560',
    projectId: 'dulcineia-ee8f1',
    storageBucket: 'dulcineia-ee8f1.appspot.com',
    iosClientId: '737119538560-ent9m94d29as9n8k8boap6sancib3v9u.apps.googleusercontent.com',
    iosBundleId: 'com.example.diagnostico',
  );
}
